title: qwguo themes
logo: qwguo
favicon: image/favicon.ico   ## size:32px*32px,`.ico` is recommended,please put image into the theme folder `/jacman/source/img`.
apple_icon: image/favicon.png ## size:114px*114px,please put image into the theme folder `/jacman/source/img`.

menus:
  主页: /
  关于: /about
  categories: /categories
  tags: /tags
  archives: /archives

# Sidebar
sidebar:
  show: true                               #是否显示侧边栏 true, false
  position: left                           #侧边栏的位置 left, right
# 侧边栏部件
widgets:
- author                                    #博主介绍
- category                                  #分类
# - tags                                       #标签
- archive                                   #归档
- recentPosts                              #最新文章
- tagsCloud                                  #标签云

author:
  portrait: /image/author.jpg
  name: 祁维国
  intro: 一台电脑，一根网线，能够宅到天昏地暗
  weibo: false
  weixin: false
  QQ: false
  douban: false
  zhihu: https://www.zhihu.com/people/qwguo
  email: 75624839@qq.com
  twitter: false
  github:  https://github.com/qwguo
  facebook: false
  linkedin: false
  stackoverflow: false

tags:
  show_count: true

archive:
  show_count: false
  archive_type: monthly


# 代码高亮主题
# available: default | night
# highlight_theme: default

