title: qwguo themes
logo: qwguo

menus:
  主页: /
  关于: /about
  categories: /categories

# Sidebar
sidebar:
  show: true                               #是否显示侧边栏 true, false
  position: left                           #侧边栏的位置 left, right
# 侧边栏部件
widgets:
- author                                    #博主介绍
- tag                                       #分类标签
- category                                  #
- archive                                   #归档标签
- recent_posts                              #最新文章
- tagcloud                                  #标签云

author:
  portrait: /image/author.jpg
  name: 祁维国
  intro: 一台电脑，一根网线，能够窄到天昏地暗
  weibo: false
  weixin: false
  QQ: false
  douban: false
  zhihu: https://www.zhihu.com/people/qwguo
  email: 75624839@qq.com
  twitter: false
  github:  https://github.com/qwguo
  facebook: false
  linkedin: false
  stackoverflow: false

tags:
  show_count: true

archive:
  show_count: false
  archive_type: monthly


# 代码高亮主题
# available: default | night
# highlight_theme: default
